version: '3'

services:
  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: 
      python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - ./django:/code
    ports:
      - "8080:8080"
